### ISSUE TITLE
(Android) bij Google Drive file picker zijn midi files disabled 

### ISSUE THREAD

**Issue by sanderevers** [birkeeper/Choir-practice-midi-player#1]
Als ik op Android met de file picker een midi file wil uitkiezen kan dat wel van mijn locale files (daar kan ik zelfs alles aanklikken) maar als ik via "Browse files in other apps" naar Google Drive doorklik zijn alle midi files disabled.

Misschien op te lossen door op de input `accept=".mid"` uit te breiden naar `accept=".mid,.midi,audio/midi,audio/x-midi"`?

**Comment by birkeeper** [comment]
Heb ik aangepast in versie 1.1.1. Met mijn Adblock Browser op Adroid 14, werkt het nu. Ik kan bestanden vanuit Google drive aanklikken en laden. Heb ook aangepast dat als je een bestand aanklikt dat geen midi is, dat deze dan niet geladen wordt.

**Comment by sanderevers** [comment]
Met versie 1.1.1 verschijnt er bij mij helemaal geen file picker meer als ik op het icoontje tap. Er gebeurt niks. (terwijl er wel al "Select a midi file." naast staat)

OS: OxygenOS 13.0 (Android versie 13)
browser: Firefox 132.0

Overigens, op mijn laptop (macOS 14.7, Firefox 132.0) verschijnt er wel gewoon een file picker.
En op mijn telefoon ook als ik Chrome gebruik.

Update: ik had blijkbaar de "music and audio access" permissie uit staan op Firefox. Nu ik hem aangezet heb opent de dialog wel weer, maar als ik doorklik naar Google Drive zijn nog steeds alle files disabled.

**Comment by birkeeper** [comment]
Met Chrome werkt het wel?
Is er een optie om de juiste permissies aan te vragen? Misschien met de Permissions API (https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API). Bijvoorbeeld de "persistent-storage permission" of de "storage-access permission"

**Comment by birkeeper** [comment]
Het lijkt te liggen aan  de "Music and audio" permissie. Als die uit staat worden op de Drive geen audio files weergegeven in de mediapicker. Dit komt waarschijnlijk omdat in de input element, accept op audio/midi e.d. staat. Ik heb als test ook audio/* toegevoegd, maar dan wordt er niet meer gefilterd in Windows op midi files, maar alle audio files.  Ik heb ook een message toegevoegd die aangeeft dat je de permissie moet activeren (kan er niet op checken). Ik heb een aparte branche gemaakt, die toegankelijk is via: birkeeper.github.io/midi-player-website/Choir-practice-midi-player/midi_player.html
Werkt deze voor jou? Wat denk je. Is het beter om de accept terug te brengen naar ".mid,.midi"? Toen leek het zonder problemen te werken.

**Comment by birkeeper** [comment]
resolved in https://github.com/birkeeper/Choir-practice-midi-player/commit/8a2fe0928a85431940a30f739f8884cceba64aaf (v1.1.2)
